### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by justinfagnani** [donny-dont/Pixelate#22]
There haven't been any checkins for a while, how are things going? Does anyone have the project updated to a recent Polymer version?

**Comment by donny-dont** [comment]
Updated to 0.11.0-dev.6. Anything else you need @justinfagnani?

**Comment by justinfagnani** [comment]
Only for me to try it out. Thanks Don!

**Comment by donny-dont** [comment]
Great! Let me know what you think and if you encounter any issues. Also if you have any widget requests just open an issue.
